// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-DVzmMVHXzejp3WYYeougLd948gskYA',
    appId: '1:195651065702:web:8f268e1dcbd95d2c0a1aa7',
    messagingSenderId: '195651065702',
    projectId: 'newprojext1216',
    authDomain: 'newprojext1216.firebaseapp.com',
    storageBucket: 'newprojext1216.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB35QUYk7t8cTU0-d5lBAc299mKNPqkZYg',
    appId: '1:195651065702:android:60ee07691195bbab0a1aa7',
    messagingSenderId: '195651065702',
    projectId: 'newprojext1216',
    storageBucket: 'newprojext1216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5rZmiGibN0YcIVMnrqEePbI7zjHZI8qw',
    appId: '1:195651065702:ios:28b694259faed7260a1aa7',
    messagingSenderId: '195651065702',
    projectId: 'newprojext1216',
    storageBucket: 'newprojext1216.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5rZmiGibN0YcIVMnrqEePbI7zjHZI8qw',
    appId: '1:195651065702:ios:28b694259faed7260a1aa7',
    messagingSenderId: '195651065702',
    projectId: 'newprojext1216',
    storageBucket: 'newprojext1216.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj-DVzmMVHXzejp3WYYeougLd948gskYA',
    appId: '1:195651065702:web:31b17d3823207a980a1aa7',
    messagingSenderId: '195651065702',
    projectId: 'newprojext1216',
    authDomain: 'newprojext1216.firebaseapp.com',
    storageBucket: 'newprojext1216.firebasestorage.app',
  );

}